/**
 * prompts/feedback.prompt.ts
 *
 * Prompts for the Final Feedback Engine (Interview DNA).
 *
 * TODO (Member 3 — AI): Implement these prompts to:
 *   - Accept the complete final InterviewState as context
 *   - Generate strengths with evidence citations from specific answers
 *   - Generate knowledge gaps with specific curriculum day references
 *   - Generate a prioritised, actionable recovery plan
 *   - Write a concise narrative summary of overall performance
 *   - Request JSON output matching FinalFeedback schema
 *   - Note: overallScore is injected by the application, NOT generated by the LLM
 *
 * Owner: Member 3 (AI / Prompt Engineering)
 */

/** System prompt establishing the Feedback Engine persona */
export const FEEDBACK_SYSTEM_PROMPT = "";

/**
 * User prompt template for final feedback generation.
 * Expects placeholders: {interviewState}, {scoringBreakdown}
 */
export const FEEDBACK_USER_PROMPT = "";
