/**
 * types/interview.ts
 *
 * Shared interview domain contracts. These types are the source of truth
 * for the entire INTERVUE application. All three team members depend on
 * these definitions — coordinate before modifying.
 *
 * Owner: Shared (types/ directory)
 */

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

/** Difficulty level for interview questions: 1 = easiest, 5 = hardest */
export type DifficultyLevel = 1 | 2 | 3 | 4 | 5;

/** Confidence level derived from evidence count and answer quality */
export type ConfidenceLevel = "low" | "medium" | "high";

// ---------------------------------------------------------------------------
// Adaptive Decision
// ---------------------------------------------------------------------------

/**
 * The AI Decision Engine chooses one of these actions after evaluating
 * each candidate answer to determine how the interview should proceed.
 */
export type NextAction =
  | "follow_up"         // Probe deeper into the current answer
  | "probe"             // Ask a clarifying question about an ambiguous claim
  | "new_topic"         // Move to a new curriculum topic
  | "increase_difficulty" // Escalate to a harder question on the same topic
  | "decrease_difficulty" // Step down to reinforce foundational understanding
  | "cross_concept"     // Bridge to a related concept from a different day
  | "contradiction";    // Surface a detected contradiction in prior answers

// ---------------------------------------------------------------------------
// Question
// ---------------------------------------------------------------------------

/** A single interview question generated by the AI Interviewer */
export interface InterviewQuestion {
  /** Unique question identifier (UUID or deterministic hash) */
  id: string;
  /** Full text of the question displayed to the candidate */
  text: string;
  /** The primary curriculum topic this question targets */
  topic: string;
  /** The curriculum day this question maps to (1-indexed) */
  curriculumDay: number;
  /** Current difficulty level at the time the question was generated */
  difficulty: DifficultyLevel;
  /** Why this question was chosen by the Decision Engine */
  reason: string;
  /** Concepts the AI expects a strong answer to mention */
  expectedConcepts: string[];
}

// ---------------------------------------------------------------------------
// Answer Evaluation
// ---------------------------------------------------------------------------

/** Structured evaluation of a candidate's answer, produced by the AI Evaluator */
export interface AnswerEvaluation {
  /**
   * Technical correctness of the answer (0–10).
   * Weight in final score: 35%
   */
  correctness: number;
  /**
   * Quality of reasoning and logical structure (0–10).
   * Weight in final score: 25%
   */
  reasoning: number;
  /**
   * Depth of knowledge demonstrated beyond surface-level recall (0–10).
   * Weight in final score: 20%
   */
  depth: number;
  /**
   * Clarity and articulation of the response (0–10).
   * Weight in final score: 10%
   */
  communication: number;
  /**
   * Practical engineering judgement and real-world applicability (0–10).
   * Weight in final score: 10%
   */
  engineering: number;
  /** Concepts from expectedConcepts that the candidate addressed */
  coveredConcepts: string[];
  /** Concepts from expectedConcepts that the candidate missed */
  missingConcepts: string[];
  /** Factually incorrect claims or conceptual errors in the answer */
  misconceptions: string[];
  /** The Decision Engine action triggered by this evaluation */
  nextAction: NextAction;
}

// ---------------------------------------------------------------------------
// Knowledge Twin
// ---------------------------------------------------------------------------

/**
 * The AI's running estimate of candidate knowledge for a specific topic.
 * Updated after every evaluated answer.
 */
export interface TopicKnowledge {
  /** Curriculum topic name */
  topic: string;
  /**
   * Estimated knowledge score for this topic (0–10).
   * Derived from weighted evaluation scores across all related questions.
   */
  estimatedScore: number;
  /**
   * How confident the AI is in its estimate.
   * "low" = 1–2 evidence points, "medium" = 3–4, "high" = 5+
   */
  confidence: ConfidenceLevel;
  /** Number of questions answered that contribute evidence for this topic */
  evidenceCount: number;
}

// ---------------------------------------------------------------------------
// Turn
// ---------------------------------------------------------------------------

/** A single question-answer-evaluation round in the interview */
export interface InterviewTurn {
  question: InterviewQuestion;
  /** Raw text submitted by the candidate */
  answer: string;
  evaluation: AnswerEvaluation;
}

// ---------------------------------------------------------------------------
// Interview State
// ---------------------------------------------------------------------------

/**
 * The authoritative runtime state of an active interview session.
 * Maintained server-side; a lightweight subset is sent to the client.
 */
export interface InterviewState {
  /** Unique session identifier (UUID) */
  sessionId: string;
  /** Identifies the candidate being interviewed */
  candidateId: string;
  /** Total number of questions asked so far */
  questionCount: number;
  /** Distinct curriculum days covered so far */
  daysCovered: number[];
  /** Topic currently being explored */
  currentTopic: string;
  /** Current adaptive difficulty level */
  difficulty: DifficultyLevel;
  /** Topics/concepts where strong performance has been demonstrated */
  strengths: string[];
  /** Topics/concepts where significant gaps have been detected */
  knowledgeGaps: string[];
  /** Detected misconceptions accumulated across all turns */
  misconceptions: string[];
  /** Claims made by the candidate that may be tested for consistency */
  candidateClaims: string[];
  /** Detected internal contradictions across prior answers */
  contradictions: string[];
  /** Live Candidate Knowledge Twin — updated after each turn */
  knowledgeTwin: TopicKnowledge[];
  /** Full history of all turns in this session */
  questionHistory: InterviewTurn[];
}
