/**
 * ai/feedback-generator.ts
 *
 * Final Feedback Engine — Interview DNA
 *
 * Generates the complete structured feedback report at the end of an
 * interview session. The feedback includes an overall score, strengths,
 * knowledge gaps, a final Knowledge Twin snapshot, and a prioritised
 * recovery plan for the candidate.
 *
 * Owner: Member 3 (AI / Prompt Engineering)
 */

import type { InterviewState } from "@/types/interview";
import type { FinalFeedback, StrengthEntry, GapEntry, RecoveryItem } from "@/types/feedback";
import { calculateSessionScore } from "@/lib/scoring";
import { nowISO } from "@/lib/utils";
import { createJsonCompletion } from "@/lib/llm";

// ---------------------------------------------------------------------------
// Internal LLM Output Type
// ---------------------------------------------------------------------------

interface LLMFeedbackOutput {
  summary: string;
  strengths: StrengthEntry[];
  gaps: GapEntry[];
  recoveryPlan: RecoveryItem[];
}

// ---------------------------------------------------------------------------
// Function
// ---------------------------------------------------------------------------

/**
 * Generates the final Interview DNA feedback report for a completed session.
 *
 * overallScore is calculated deterministically via calculateSessionScore(),
 * NOT generated by the LLM, to ensure reproducibility.
 *
 * @param state - The final InterviewState after all questions have been asked
 * @returns FinalFeedback — the complete structured report
 */
export async function generateFinalFeedback(
  state: InterviewState
): Promise<FinalFeedback> {
  // Always calculate the score deterministically — never trust the LLM for this
  const overallScore = calculateSessionScore(
    state.questionHistory.map((t) => t.evaluation)
  );

  // Build a transcript summary for the LLM
  const transcript = state.questionHistory
    .map(
      (turn, i) =>
        `Q${i + 1} [${turn.question.topic}, Day ${turn.question.curriculumDay}, Difficulty ${turn.question.difficulty}]:\n` +
        `Question: ${turn.question.text}\n` +
        `Answer: ${turn.answer.slice(0, 300)}${turn.answer.length > 300 ? "..." : ""}\n` +
        `Scores — Correctness: ${turn.evaluation.correctness}/10, Reasoning: ${turn.evaluation.reasoning}/10, ` +
        `Depth: ${turn.evaluation.depth}/10, Communication: ${turn.evaluation.communication}/10, Engineering: ${turn.evaluation.engineering}/10\n` +
        `Covered: ${turn.evaluation.coveredConcepts.join(", ") || "none"}\n` +
        `Missing: ${turn.evaluation.missingConcepts.join(", ") || "none"}`
    )
    .join("\n\n---\n\n");

  const systemPrompt = `You are a senior AI engineering mentor writing a comprehensive post-interview feedback report for a learner.

Your feedback must be:
- Specific and evidence-based (reference actual answers from the transcript)
- Constructive and encouraging even when identifying gaps
- Actionable (recovery plan items must be concrete, not vague)
- Professional in tone

Return ONLY valid JSON. No markdown, no extra text.`;

  const userPrompt = `Generate a final feedback report for this completed technical interview.

CANDIDATE: ${state.candidateId}
OVERALL SCORE: ${overallScore}/100
TOTAL QUESTIONS: ${state.questionHistory.length}
CURRICULUM DAYS COVERED: ${state.daysCovered.join(", ")}
IDENTIFIED STRENGTHS: ${state.strengths.join(", ") || "None explicitly identified"}
KNOWLEDGE GAPS: ${state.knowledgeGaps.join(", ") || "None explicitly identified"}
MISCONCEPTIONS: ${state.misconceptions.slice(0, 5).join("; ") || "None detected"}

FULL INTERVIEW TRANSCRIPT:
${transcript}

Return this exact JSON structure:
{
  "summary": "3-4 sentence narrative summary of the candidate's overall performance, highlighting key patterns observed",
  "strengths": [
    {
      "topic": "Topic name",
      "description": "What the candidate demonstrated well",
      "evidence": ["Specific quote or behavior from the interview that supports this"]
    }
  ],
  "gaps": [
    {
      "topic": "Topic name",
      "description": "What the candidate struggled with or lacked depth in",
      "evidence": ["Specific quote or behavior that revealed this gap"],
      "curriculumDays": [1, 5]
    }
  ],
  "recoveryPlan": [
    {
      "priority": 1,
      "topic": "Topic to address first",
      "action": "Specific, actionable step (e.g. 'Rebuild a RAG pipeline from scratch focusing on chunk sizing strategies')",
      "resources": ["Curriculum Day X", "Specific concept to review"]
    }
  ]
}

Provide 2-4 strengths, 2-4 gaps, and 3-5 recovery plan items ordered by priority.`;

  let llmOutput: LLMFeedbackOutput;

  try {
    llmOutput = await createJsonCompletion<LLMFeedbackOutput>([
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ]);
  } catch {
    // Fallback feedback if LLM call fails
    llmOutput = {
      summary: `The candidate completed ${state.questionHistory.length} questions across ${state.daysCovered.length} curriculum days, achieving an overall score of ${overallScore}/100.`,
      strengths: state.strengths.map((topic) => ({
        topic,
        description: `Demonstrated competence in ${topic}`,
        evidence: [],
      })),
      gaps: state.knowledgeGaps.map((topic) => ({
        topic,
        description: `Showed gaps in understanding of ${topic}`,
        evidence: [],
        curriculumDays: [],
      })),
      recoveryPlan: state.knowledgeGaps.map((topic, i) => ({
        priority: i + 1,
        topic,
        action: `Review and practice ${topic} concepts from the curriculum`,
        resources: [],
      })),
    };
  }

  return {
    sessionId: state.sessionId,
    candidateId: state.candidateId,
    generatedAt: nowISO(),
    overallScore,
    summary: llmOutput.summary,
    strengths: llmOutput.strengths,
    gaps: llmOutput.gaps,
    knowledgeTwin: state.knowledgeTwin,
    recoveryPlan: llmOutput.recoveryPlan,
    daysCovered: state.daysCovered,
    totalQuestions: state.questionCount,
  };
}
