/**
 * ai/feedback-generator.ts
 *
 * Final Feedback Engine — Interview DNA
 *
 * Generates the complete structured feedback report at the end of an
 * interview session. The feedback includes an overall score, strengths,
 * knowledge gaps, a final Knowledge Twin snapshot, and a prioritised
 * recovery plan for the candidate.
 *
 * Owner: Member 3 (AI / Prompt Engineering)
 *
 * TODO: Implement generateFinalFeedback() using the LLM client:
 *   1. Build a comprehensive prompt from the full InterviewState
 *   2. Call createChatCompletion() with jsonMode: true
 *   3. Parse and validate against FinalFeedbackSchema
 *   4. Inject the deterministic overallScore from lib/scoring.ts
 *   5. Return validated FinalFeedback
 */

import type { InterviewState } from "@/types/interview";
import type { FinalFeedback } from "@/types/feedback";
import { calculateSessionScore } from "@/lib/scoring";
import { nowISO } from "@/lib/utils";

// ---------------------------------------------------------------------------
// Function
// ---------------------------------------------------------------------------

/**
 * Generates the final Interview DNA feedback report for a completed session.
 *
 * @param state - The final InterviewState after all questions have been asked
 * @returns FinalFeedback — the complete structured report
 *
 * TODO: Replace placeholder return with real LLM-powered feedback generation.
 *   Note: overallScore MUST be calculated via calculateSessionScore(),
 *   NOT generated by the LLM, to ensure determinism.
 */
export async function generateFinalFeedback(
  state: InterviewState
): Promise<FinalFeedback> {
  const overallScore = calculateSessionScore(
    state.questionHistory.map((t) => t.evaluation)
  );

  // TODO: Implement real LLM-based narrative feedback and recovery plan
  return {
    sessionId: state.sessionId,
    candidateId: state.candidateId,
    generatedAt: nowISO(),
    overallScore,
    summary: "Not implemented — generateFinalFeedback() is a scaffold stub.",
    strengths: [],
    gaps: [],
    knowledgeTwin: state.knowledgeTwin,
    recoveryPlan: [],
    daysCovered: state.daysCovered,
    totalQuestions: state.questionCount,
  };
}
